require 'itsalive/version'
require 'itsalive/defaults'
require 'itsalive/error'
require 'itsalive/activation_functions'
require 'itsalive/weight_functions'
require 'itsalive/block_evaluator'
require 'itsalive/settings'
require 'itsalive/synapse'
require 'itsalive/neuron'
require 'itsalive/input_neuron'
require 'itsalive/output_neuron'
require 'itsalive/layer'
require 'itsalive/input_layer'
require 'itsalive/output_layer'
require 'itsalive/network'

module ItsAlive
  autoload :Defaults, 'itsalive/defaults'
  autoload :Error, 'itsalive/error'
  autoload :ActivationFunctions, 'itsalive/activation_functions'
  autoload :WeightFunctions, 'itsalive/weight_functions'
  autoload :BlockEvaluator, 'itsalive/block_evaluator'
  autoload :Settings, 'itsalive/settings'
  autoload :Synapse, 'itsalive/synapse'
  autoload :Neuron, 'itsalive/neuron'
  autoload :InputNeuron, 'itsalive/input_neuron'
  autoload :OutputNeuron, 'itsalive/output_neuron'
  autoload :Layer, 'itsalive/layer'
  autoload :InputLayer, 'itsalive/input_layer'
  autoload :OutputLayer, 'itsalive/output_layer'
  autoload :Network, 'itsalive/network'
end
